version: '3.8'

services:
  sanctum:
    image: postgres:16
    container_name: sanctum
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5416:5432"

  api:
    build: ./api
    container_name: api
    ports:
      - "8001:8000"
    env_file:
      - ./api/prod.env
    tty: true
    depends_on:
      - sanctum
  
  app:
    build: ./app
    container_name: app
    ports:
      - "3001:3000"
    env_file:
      - ./app/prod.env
    depends_on:
      - api
      - sanctum

  trainer:
    build: ./trainer
    container_name: trainer
    tty: true
    depends_on:
      - sanctum

networks:
  tc5:
    driver: bridge

volumes:
  postgres_data:
    driver: local
