version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: sanctum
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5416:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  api:
    build: ./api
    container_name: api
    ports:
      - "8001:8000"
    volumes:
      - ./api:/home/lightfm
    env_file:
      - ./api/prod.env
    tty: true
    depends_on:
      - postgres
    

  trainer:
    build: ./trainer
    container_name: trainer
    volumes:
      - ./trainer:/home/lightfm
    tty: true
    depends_on:
      - postgres

networks:
  tc5:
    driver: bridge

volumes:
  postgres_data:
    driver: local
