version: '3.8'

services:
  sanctum:
    image: postgres:16
    container_name: sanctum
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5416:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - tc5

  api:
    build: ./api
    container_name: api
    ports:
      - "8001:8000"
    volumes:
      - ./api:/home/lightfm
    env_file:
      - ./api/prod.env
    tty: true
    networks:
      - tc5
    depends_on:
      - sanctum
    

  trainer:
    build: ./trainer
    container_name: trainer
    volumes:
      - ./trainer:/home/lightfm
    tty: true
    networks:
      - tc5
    depends_on:
      - sanctum

  app:
    build: ./app
    container_name: app
    ports:
      - "3001:3000"
    env_file:
      - ./app/prod.env
    depends_on:
      - api
      - sanctum
    volumes:
      - ./app:/app
      - ./app/node_modules:/app/node_modules
    networks:
      - tc5
    command: npm run dev

networks:
  tc5:
    driver: bridge

volumes:
  postgres_data:
    driver: local
